### ISSUE TITLE
Mettre en place le système de sondage

### ISSUE THREAD

**Issue by ArthusWQZ** [dataforgoodfr/batch11_basta#32]
Mettre en place un système de sondage :
- Sondage par réactions : réaction unique par utilisateur optionnelle
- Récupération des résultats lors de la génération de la synthèse (donc stocker les IDs dans la configuration)

**Comment by Hkllopp** [comment]
Update : 
Les sondages seront intégrés dans le script

**Comment by Hkllopp** [comment]
Done ! ✅ 🥳
